### PR TITLE
Create contact form with validation

### PR DESCRIPTION
**Pull request by Duretitibesso3**
- Alfred and I were able to implement the following feature

1.  The contact form is located in the footer:
2.  The name field accepts up to 30 chars.
3. The email field accepts only emails.
4. The message field accepts up to 500 chars.
5. All fields have placeholder text.
6. All fields have the correct type.
7. A user cannot submit the form if one or more of the fields is empty.
8. Collect data by using the [Formspree service](https://formspree.io/html).
9. I used Flexbox to layout items in the contact form.
10. I stuck to the design as much as I could
11. I Implemented the button interactions (enable, hover, etc.).

### CODE REVIEW

**Review by danmainah — CHANGES_REQUESTED** [review]
Hi @Duretitibesso3 and @Alfred-KInyua, 

Good job so far!
There are some issues that you still need to work on to go to the next project but you are almost there!

## Highlights
✔️ No linter errors
✔️ Github flow was correctly used
✔️  Good PR and Description


# Required Changes ♻️

- [ ] Kindly check on your form design, there are small differences that can be corrected check the comparison below to get a better view of what needs to be fixed:


Figma Design          |  Your design     
:-------------------------:|:-------------------------:
image |  image



_Check the comments under the review._

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s).

**Review by nicupop729 — CHANGES_REQUESTED** [review]
Hi @Duretitibesso3 & @Alfred-KInyua, 

Great work on making the changes requested by a previous reviewer 👏 
You've done well implementing some of the requested changes, but there are still some which aren't addressed yet.



## Highlights
 - [X] Correct GitHub flow practice :heavy_check_mark:
 - [X] Good commit messages :heavy_check_mark:
 - [X] Professional README :heavy_check_mark:
 - [X] Linters are passing :heavy_check_mark:

 ## Required Changes ♻️
**Because the contact form was created in a previous pull request and not in this one, I am not able to provide inline comments, so I will just write the comments here:**

As we need to follow the project requirements and the Figma design (we may think that a client provided us with the design from Figma to create his web page, so we need to follow our client requirements) kindly I ask the following:

- [ ] Place the contact button on the left side of the form;
- [ ] Give a bigger top margin to the form to have more white space between the form and the previous section;
- [ ] Give a bigger bottom margin to the form or to the button in order to have more space between the button and the divider bar;

Your implementation | Figma Design
:------:|:------:
image | image
_Check the comments under the review._

## Optional suggestions 

- [ ] The Figma design provided the name and email as just an example of how someone can write his email and name there. But the placeholders should be for the name: 'Write your name', and for the email: 'Write your email' or something similar; I strongly recommend changing the placeholders for email and name;



_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._


Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**


------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

**Comment by Duretitibesso3** [comment]
Fixed the reviewer requirements
- Place the contact button on the left side of the form;
-  Give a bigger top margin to the form to have more white space between the form and the previous section;
-  Give a bigger bottom margin to the form or to the button in order to have more space between the button and the divider bar;

**Review by codepantha — APPROVED** [review]
Hi @Duretitibesso3 and @Alfred-KInyua 👋,

## STATUS: APPROVED ✔️  

Weldone implementing all the required changes 👏 👏 
Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 



Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

**Pull request merged**
